import { ServantData } from "./types";

export const SERVANTS: ServantData[] = [
  {
    name: "Artoria Pendragon",
    aliases: [
      "Altria Pendragon",
    ],
    footId: 100100,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Artoria Pendragon (Alter)",
    aliases: [
      "Altria Pendragon (Alter)",
      "Salter",
    ],
    footId: 100200,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Artoria Pendragon (Lily)",
    aliases: [
      "Altria Pendragon (Lily)",
    ],
    footId: 100300,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Nero Claudius",
    aliases: [],
    footId: 100500,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Nero Claudius (Bride)",
    aliases: [],
    footId: 100600,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Gawain",
    aliases: [],
    footId: 100700,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Siegfried",
    aliases: [],
    footId: 100800,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Mordred",
    aliases: [],
    footId: 100900,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Elisabeth Bathory (Brave)",
    aliases: [],
    footId: 101000,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Bedivere",
    aliases: [],
    footId: 101200,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Gaius Julius Caesar",
    aliases: [],
    footId: 101300,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Fergus mac Roich",
    aliases: [],
    footId: 101400,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Altera",
    aliases: [],
    footId: 101800,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Rama",
    aliases: [],
    footId: 101900,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Lancelot (Saber)",
    aliases: [],
    footId: 102000,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Gilles de Rais (Saber)",
    aliases: [],
    footId: 102200,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Chevalier d'Eon",
    aliases: [],
    footId: 102600,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Okita Souji",
    aliases: [],
    footId: 102700,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Ryougi Shiki (Saber)",
    aliases: [],
    footId: 102800,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Arthur Pendragon (Prototype)",
    aliases: [],
    footId: 102900,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Suzuka Gozen",
    aliases: [],
    footId: 103000,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Frankenstein (Saber)",
    aliases: [],
    footId: 103100,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Yagyu Tajima-no-kami Munenori",
    aliases: [],
    footId: 103200,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Sigurd",
    aliases: [],
    footId: 103300,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Queen Medb (Saber)",
    aliases: [],
    footId: 103400,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Diarmuid Ua Duibhne (Saber)",
    aliases: [],
    footId: 103500,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Prince of Lan Ling",
    aliases: [],
    footId: 103600,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Beni-Enma",
    aliases: [],
    footId: 103700,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Jason",
    aliases: [],
    footId: 103800,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Lakshmi Bai",
    aliases: [],
    footId: 103900,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Katsushika Hokusai (Saber)",
    aliases: [],
    footId: 104000,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Astolfo (Saber)",
    aliases: [],
    footId: 104100,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Dioscuri",
    aliases: [],
    footId: 104200,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Roland",
    aliases: [],
    footId: 104300,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Saito Hajime",
    aliases: [],
    footId: 104400,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Tomoe Gozen (Saber)",
    aliases: [],
    footId: 104500,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Ibuki-Douji",
    aliases: [],
    footId: 104600,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Watanabe-no-Tsuna",
    aliases: [],
    footId: 104700,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Karna (Santa)",
    aliases: [],
    footId: 104800,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Senji Muramasa",
    aliases: [],
    footId: 104900,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Barghest",
    aliases: [
      "Fairy Knight Gawain",
      "Tam Lin Gawain",
    ],
    footId: 105000,
    class: 'saber',
    inNA: true,
  },
  {
    name: "Okita Souji (Saber Alter)",
    aliases: [
      "Okitan (Saber)"
    ],
    footId: 105100,
    class: 'saber',
    inNA: false,
  },
  {
    name: "Charlemagne",
    aliases: [],
    footId: 105200,
    class: 'saber',
    inNA: false,
  },
  {
    name: "Trung Sisters",
    aliases: [],
    footId: 105300,
    class: 'saber',
    inNA: false,
  },
  {
    name: "Gareth (Saber)",
    aliases: [],
    footId: 105400,
    class: 'saber',
    inNA: false,
  },
  {
    name: "Yamanami Keisuke",
    aliases: [],
    footId: 105500,
    class: 'saber',
    inNA: false,
  },
  {
    name: "Medusa (Saber)",
    aliases: [],
    footId: 100000,
    class: 'saber',
    inNA: false,
  },
  {
    name: "Setanta",
    aliases: [],
    footId: 105700,
    class: 'saber',
    inNA: false,
  },
]