import { ServantData } from "./types";

export const SERVANTS: ServantData[] = [
  {
    name: "Artoria Pendragon",
    aliases: ["Altria Pendragon"],
    footId: 100100,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Artoria Pendragon (Alter)",
    aliases: ["Altria Pendragon (Alter)", "Salter"],
    footId: 100200,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Artoria Pendragon (Lily)",
    aliases: ["Altria Pendragon (Lily)"],
    footId: 100300,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Nero Claudius",
    aliases: [],
    footId: 100500,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Nero Claudius (Bride)",
    aliases: [],
    footId: 100600,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Gawain",
    aliases: [],
    footId: 100700,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Siegfried",
    aliases: [],
    footId: 100800,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Mordred",
    aliases: [],
    footId: 100900,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Elisabeth Bathory (Brave)",
    aliases: [],
    footId: 101000,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Bedivere",
    aliases: [],
    footId: 101200,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Gaius Julius Caesar",
    aliases: [],
    footId: 101300,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Fergus mac Roich",
    aliases: [],
    footId: 101400,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Altera",
    aliases: [],
    footId: 101800,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Rama",
    aliases: [],
    footId: 101900,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Lancelot (Saber)",
    aliases: [],
    footId: 102000,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Gilles de Rais (Saber)",
    aliases: [],
    footId: 102200,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Chevalier d'Eon",
    aliases: [],
    footId: 102600,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Okita Souji",
    aliases: [],
    footId: 102700,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Ryougi Shiki (Saber)",
    aliases: [],
    footId: 102800,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Arthur Pendragon (Prototype)",
    aliases: [],
    footId: 102900,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Suzuka Gozen",
    aliases: [],
    footId: 103000,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Frankenstein (Saber)",
    aliases: ["Summer Frankenstein"],
    footId: 103100,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Yagyu Tajima-no-kami Munenori",
    aliases: [],
    footId: 103200,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Sigurd",
    aliases: [],
    footId: 103300,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Queen Medb (Saber)",
    aliases: ["Summer Medb"],
    footId: 103400,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Diarmuid Ua Duibhne (Saber)",
    aliases: [],
    footId: 103500,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Prince of Lan Ling",
    aliases: [],
    footId: 103600,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Beni-Enma",
    aliases: [],
    footId: 103700,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Jason",
    aliases: [],
    footId: 103800,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Lakshmi Bai",
    aliases: [],
    footId: 103900,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Katsushika Hokusai (Saber)",
    aliases: ["Summer Hokusai"],
    footId: 104000,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Astolfo (Saber)",
    aliases: [],
    footId: 104100,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Dioscuri",
    aliases: [],
    footId: 104200,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Roland",
    aliases: [],
    footId: 104300,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Saito Hajime",
    aliases: [],
    footId: 104400,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Tomoe Gozen (Saber)",
    aliases: ["Summer Tomoe"],
    footId: 104500,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Ibuki-Douji",
    aliases: [],
    footId: 104600,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Watanabe-no-Tsuna",
    aliases: [],
    footId: 104700,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Karna (Santa)",
    aliases: ["Santa Karna"],
    footId: 104800,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Senji Muramasa",
    aliases: [],
    footId: 104900,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Barghest",
    aliases: ["Fairy Knight Gawain", "Tam Lin Gawain"],
    footId: 105000,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Okita Souji Alter (Saber)",
    aliases: ["Summer Okitan"],
    footId: 105100,
    servantClass: "saber",
    inNa: false,
  },
  {
    name: "Charlemagne",
    aliases: [],
    footId: 105200,
    servantClass: "saber",
    inNa: false,
  },
  {
    name: "Trung Sisters",
    aliases: [],
    footId: 105300,
    servantClass: "saber",
    inNa: false,
  },
  {
    name: "Gareth (Saber)",
    aliases: ["Summer Gareth"],
    footId: 105400,
    servantClass: "saber",
    inNa: false,
  },
  {
    name: "Yamanami Keisuke",
    aliases: [],
    footId: 105500,
    servantClass: "saber",
    inNa: false,
  },
  {
    name: "Medusa (Saber)",
    aliases: [],
    footId: 105600,
    servantClass: "saber",
    inNa: false,
  },
  {
    name: "Setanta",
    aliases: [],
    footId: 105700,
    servantClass: "saber",
    inNa: false,
  },
  {
    name: "Emiya",
    aliases: [],
    footId: 200100,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Gilgamesh",
    aliases: [],
    footId: 200200,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Robin Hood",
    aliases: [],
    footId: 200300,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Atalante",
    aliases: [],
    footId: 200500,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "David",
    aliases: [],
    footId: 200600,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Tristan",
    aliases: [],
    footId: 200800,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Orion",
    aliases: ["Artemis"],
    footId: 200900,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Billy the Kid",
    aliases: [],
    footId: 201000,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Nikola Tesla",
    aliases: [],
    footId: 201100,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Euryale",
    aliases: [],
    footId: 201200,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Arash",
    aliases: [],
    footId: 201300,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Tawara Touta",
    aliases: [],
    footId: 201400,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Arjuna",
    aliases: [],
    footId: 201500,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Emiya (Alter)",
    aliases: ["Demiya"],
    footId: 201600,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Gilgamesh (Child)",
    aliases: ["Kid Gil"],
    footId: 201800,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Ishtar",
    aliases: [],
    footId: 202000,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Tomoe Gozen",
    aliases: ["Archer of Inferno"],
    footId: 202100,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Attila the San(ta)",
    aliases: ["Santa Altera", "Santera"],
    footId: 202200,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "James Moriarty",
    aliases: ["Archer of Shinjuku"],
    footId: 202300,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Oda Nobunaga",
    aliases: [],
    footId: 202400,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Anne Bonny & Mary Read (Archer)",
    aliases: ["Summer Anne & Mary"],
    footId: 202500,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Artoria Pendragon (Archer)",
    aliases: ["Altria Pendragon (Archer)", "Archuria", "Squirtoria"],
    footId: 202600,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Chloe von Einzbern",
    aliases: ["Kuro"],
    footId: 202700,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Helena Blavatsky",
    aliases: ["Summer Helena"],
    footId: 202800,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Asagami Fujino",
    aliases: [],
    footId: 202900,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Chiron",
    aliases: [],
    footId: 203000,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Napoleon",
    aliases: [],
    footId: 203100,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Jeanne d'Arc (Archer)",
    aliases: ["Summer Jeanne"],
    footId: 203200,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Asvatthaman",
    aliases: [],
    footId: 203300,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "William Tell",
    aliases: [],
    footId: 203400,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Paris",
    aliases: [],
    footId: 203500,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Osakabehime (Archer)",
    aliases: ["Summer Osakabehime", "Summer Okki", "Summer Batty"],
    footId: 203600,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Calamity Jane",
    aliases: [],
    footId: 203700,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Super Orion",
    aliases: [],
    footId: 203800,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Florence Nightingale (Santa)",
    aliases: [],
    footId: 203900,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Sei Shounagon",
    aliases: ["Nagiko"],
    footId: 204000,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Oda Nobukatsu",
    aliases: [],
    footId: 204100,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Illyasviel von Einzbern (Archer)",
    aliases: ["Summer Illya"],
    footId: 204200,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Baobhan Sith",
    aliases: ["Fairy Knight Tristan", "Tam Lin Tristan"],
    footId: 204300,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Anastasia & Viy",
    aliases: ["Summer Anastasia"],
    footId: 204400,
    servantClass: "archer",
    inNa: false,
  },
  {
    name: "Zenobia",
    aliases: [],
    footId: 204500,
    servantClass: "archer",
    inNa: false,
  },
  {
    name: "Minamoto no Tametomo",
    aliases: [],
    footId: 204600,
    servantClass: "archer",
    inNa: false,
  },
  {
    name: "Takasugi Shinsaku",
    aliases: [],
    footId: 204700,
    servantClass: "archer",
    inNa: false,
  },
  {
    name: "Durga",
    aliases: [],
    footId: 204800,
    servantClass: "archer",
    inNa: false,
  },
  {
    name: "Cu Chulainn",
    aliases: [],
    footId: 300100,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Diarmuid Ua Duibhne",
    aliases: [],
    footId: 300200,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Vlad III (EXTRA)",
    aliases: [],
    footId: 300300,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Karna",
    aliases: [],
    footId: 300400,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Elisabeth Bathory",
    aliases: [],
    footId: 300500,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Musashibou Benkei",
    aliases: [],
    footId: 300600,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Cu Chulainn (Prototype)",
    aliases: [],
    footId: 300700,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Enkidu",
    aliases: [],
    footId: 300800,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Leonidas I",
    aliases: [],
    footId: 300900,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Romulus",
    aliases: [],
    footId: 301000,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Fionn mac Cumhaill",
    aliases: [],
    footId: 301100,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Brynhild",
    aliases: [],
    footId: 301200,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Scathach",
    aliases: [],
    footId: 301300,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Houzouin Inshun",
    aliases: [],
    footId: 301400,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Hektor",
    aliases: [],
    footId: 301600,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Li Shuwen",
    aliases: [],
    footId: 301700,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Artoria Pendragon Alter (Lancer)",
    aliases: ["Altria Pendragon Alter (Lancer)", "Lalter"],
    footId: 301900,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Artoria Pendragon (Lancer)",
    aliases: ["Altria Pendragon (Lancer)", "Lartoria"],
    footId: 302000,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Tamamo-no-Mae (Lancer)",
    aliases: ["Summer Tamamo"],
    footId: 302400,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Kiyohime (Lancer)",
    aliases: ["Summer Kiyohime"],
    footId: 302500,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Jeanne d'Arc Alter Santa Lily",
    aliases: [],
    footId: 302600,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Medusa (Lancer)",
    aliases: ["Ana", "Medusa Lily"],
    footId: 302700,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Jaguar Warrior",
    aliases: [],
    footId: 302800,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Minamoto-no-Raikou (Lancer)",
    aliases: ["Summer Raikou"],
    footId: 302900,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Parvati",
    aliases: [],
    footId: 303000,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Nezha",
    aliases: [],
    footId: 303100,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Ereshkigal",
    aliases: [],
    footId: 303200,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Valkyrie",
    aliases: ["Ortlinde", "Hildr", "Thrud"],
    footId: 303300,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Ibaraki-Douji (Lancer)",
    aliases: ["Summer Ibaraki", "Summer Banana"],
    footId: 303400,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Qin Liangyu",
    aliases: [],
    footId: 303500,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Bradamante",
    aliases: [],
    footId: 303600,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Nagao Kagetora",
    aliases: [],
    footId: 303800,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Gareth",
    aliases: [],
    footId: 303900,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Mysterious Alter Ego Λ",
    aliases: ["Summer Melt", "Mysterious Alter Ego Lambda"],
    footId: 304000,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Caenis",
    aliases: [],
    footId: 304100,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Romulus=Quirinus",
    aliases: [],
    footId: 304200,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Utsumi Erice",
    aliases: [],
    footId: 304300,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Yu Mei-ren (Lancer)",
    aliases: ["Summer Gucchan", "Summer Yu"],
    footId: 304400,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Vritra",
    aliases: [],
    footId: 304600,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Percival",
    aliases: [],
    footId: 304700,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Melusine",
    aliases: ["Fairy Knight Lancelot", "Tam Lin Lancelot"],
    footId: 304800,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Mary Anning",
    aliases: [],
    footId: 304900,
    servantClass: "lancer",
    inNa: false,
  },
  {
    name: "Sakamoto Ryouma (Lancer)",
    aliases: [],
    footId: 305000,
    servantClass: "lancer",
    inNa: false,
  },
  {
    name: "Don Quixote",
    aliases: [],
    footId: 305100,
    servantClass: "lancer",
    inNa: false,
  },
  {
    name: "Britomart",
    aliases: [],
    footId: 305300,
    servantClass: "lancer",
    inNa: false,
  },
  {
    name: "Bhima",
    aliases: [],
    footId: 305400,
    servantClass: "lancer",
    inNa: false,
  },
];
