import { ServantData } from "./types";

export const SERVANTS: ServantData[] = [
  {
    name: "Artoria Pendragon",
    aliases: ["Altria Pendragon"],
    footId: 100100,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Artoria Pendragon (Alter)",
    aliases: ["Altria Pendragon (Alter)", "Salter"],
    footId: 100200,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Artoria Pendragon (Lily)",
    aliases: ["Altria Pendragon (Lily)"],
    footId: 100300,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Nero Claudius",
    aliases: [],
    footId: 100500,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Nero Claudius (Bride)",
    aliases: [],
    footId: 100600,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Gawain",
    aliases: [],
    footId: 100700,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Siegfried",
    aliases: [],
    footId: 100800,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Mordred",
    aliases: [],
    footId: 100900,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Elisabeth Bathory (Brave)",
    aliases: [],
    footId: 101000,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Bedivere",
    aliases: [],
    footId: 101200,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Gaius Julius Caesar",
    aliases: [],
    footId: 101300,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Fergus mac Roich",
    aliases: [],
    footId: 101400,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Altera",
    aliases: [],
    footId: 101800,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Rama",
    aliases: [],
    footId: 101900,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Lancelot (Saber)",
    aliases: [],
    footId: 102000,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Gilles de Rais (Saber)",
    aliases: [],
    footId: 102200,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Chevalier d'Eon",
    aliases: [],
    footId: 102600,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Okita Souji",
    aliases: [],
    footId: 102700,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Ryougi Shiki (Saber)",
    aliases: [],
    footId: 102800,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Arthur Pendragon (Prototype)",
    aliases: [],
    footId: 102900,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Suzuka Gozen",
    aliases: [],
    footId: 103000,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Frankenstein (Saber)",
    aliases: ["Summer Frankenstein"],
    footId: 103100,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Yagyu Tajima-no-kami Munenori",
    aliases: [],
    footId: 103200,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Sigurd",
    aliases: [],
    footId: 103300,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Queen Medb (Saber)",
    aliases: ["Summer Medb"],
    footId: 103400,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Diarmuid Ua Duibhne (Saber)",
    aliases: [],
    footId: 103500,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Prince of Lan Ling",
    aliases: [],
    footId: 103600,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Beni-Enma",
    aliases: [],
    footId: 103700,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Jason",
    aliases: [],
    footId: 103800,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Lakshmi Bai",
    aliases: [],
    footId: 103900,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Katsushika Hokusai (Saber)",
    aliases: ["Summer Hokusai"],
    footId: 104000,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Astolfo (Saber)",
    aliases: [],
    footId: 104100,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Dioscuri",
    aliases: [],
    footId: 104200,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Roland",
    aliases: [],
    footId: 104300,
    servantClass: "saber",
    inNa: false,
  },
  {
    name: "Saito Hajime",
    aliases: [],
    footId: 104400,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Tomoe Gozen (Saber)",
    aliases: ["Summer Tomoe"],
    footId: 104500,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Ibuki-Douji",
    aliases: [],
    footId: 104600,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Watanabe-no-Tsuna",
    aliases: [],
    footId: 104700,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Karna (Santa)",
    aliases: [],
    footId: 104800,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Senji Muramasa",
    aliases: [],
    footId: 104900,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Barghest",
    aliases: ["Fairy Knight Gawain", "Tam Lin Gawain"],
    footId: 105000,
    servantClass: "saber",
    inNa: true,
  },
  {
    name: "Okita Souji (Saber Alter)",
    aliases: ["Summer Okitan"],
    footId: 105100,
    servantClass: "saber",
    inNa: false,
  },
  {
    name: "Charlemagne",
    aliases: [],
    footId: 105200,
    servantClass: "saber",
    inNa: false,
  },
  {
    name: "Trung Sisters",
    aliases: [],
    footId: 105300,
    servantClass: "saber",
    inNa: false,
  },
  {
    name: "Gareth (Saber)",
    aliases: ["Summer Gareth"],
    footId: 105400,
    servantClass: "saber",
    inNa: false,
  },
  {
    name: "Yamanami Keisuke",
    aliases: [],
    footId: 105500,
    servantClass: "saber",
    inNa: false,
  },
  {
    name: "Medusa (Saber)",
    aliases: [],
    footId: 105600,
    servantClass: "saber",
    inNa: false,
  },
  {
    name: "Setanta",
    aliases: [],
    footId: 105700,
    servantClass: "saber",
    inNa: false,
  },
  {
    name: "Emiya",
    aliases: [],
    footId: 200100,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Gilgamesh",
    aliases: [],
    footId: 200200,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Robin Hood",
    aliases: [],
    footId: 200300,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Atalante",
    aliases: [],
    footId: 200500,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "David",
    aliases: [],
    footId: 200600,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Tristan",
    aliases: [],
    footId: 200800,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Orion",
    aliases: ["Artemis"],
    footId: 200900,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Billy the Kid",
    aliases: [],
    footId: 201000,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Nikola Tesla",
    aliases: [],
    footId: 201100,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Euryale",
    aliases: [],
    footId: 201200,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Arash",
    aliases: [],
    footId: 201300,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Tawara Touta",
    aliases: [],
    footId: 201400,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Arjuna",
    aliases: [],
    footId: 201500,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Emiya (Alter)",
    aliases: ["Demiya"],
    footId: 201600,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Gilgamesh (Child)",
    aliases: ["Kid Gil"],
    footId: 201800,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Ishtar",
    aliases: [],
    footId: 202000,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Tomoe Gozen",
    aliases: ["Archer of Inferno"],
    footId: 202100,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Attila the San(ta)",
    aliases: ["Santa Altera", "Santera"],
    footId: 202200,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "James Moriarty",
    aliases: ["Archer of Shinjuku"],
    footId: 202300,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Oda Nobunaga",
    aliases: [],
    footId: 202400,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Anne Bonny & Mary Read (Archer)",
    aliases: ["Summer Anne & Mary"],
    footId: 202500,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Artoria Pendragon (Archer)",
    aliases: ["Altria Pendragon (Archer)", "Archuria", "Squirtoria"],
    footId: 202600,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Chloe von Einzbern",
    aliases: ["Kuro"],
    footId: 202700,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Helena Blavatsky (Archer)",
    aliases: ["Summer Helena"],
    footId: 202800,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Asagami Fujino",
    aliases: [],
    footId: 202900,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Chiron",
    aliases: [],
    footId: 203000,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Napoleon",
    aliases: [],
    footId: 203100,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Jeanne d'Arc (Archer)",
    aliases: ["Summer Jeanne"],
    footId: 203200,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Asvatthaman",
    aliases: [],
    footId: 203300,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "William Tell",
    aliases: [],
    footId: 203400,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Paris",
    aliases: [],
    footId: 203500,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Osakabehime (Archer)",
    aliases: ["Summer Osakabehime", "Summer Okki", "Summer Batty"],
    footId: 203600,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Calamity Jane",
    aliases: [],
    footId: 203700,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Super Orion",
    aliases: [],
    footId: 203800,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Florence Nightingale (Santa)",
    aliases: [],
    footId: 203900,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Sei Shounagon",
    aliases: ["Nagiko"],
    footId: 204000,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Oda Nobukatsu",
    aliases: [],
    footId: 204100,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Illyasviel von Einzbern (Archer)",
    aliases: ["Summer Illya"],
    footId: 204200,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Baobhan Sith",
    aliases: ["Fairy Knight Tristan", "Tam Lin Tristan"],
    footId: 204300,
    servantClass: "archer",
    inNa: true,
  },
  {
    name: "Anastasia & Viy",
    aliases: ["Summer Anastasia"],
    footId: 204400,
    servantClass: "archer",
    inNa: false,
  },
  {
    name: "Zenobia",
    aliases: [],
    footId: 204500,
    servantClass: "archer",
    inNa: false,
  },
  {
    name: "Minamoto no Tametomo",
    aliases: [],
    footId: 204600,
    servantClass: "archer",
    inNa: false,
  },
  {
    name: "Takasugi Shinsaku",
    aliases: [],
    footId: 204700,
    servantClass: "archer",
    inNa: false,
  },
  {
    name: "Durga",
    aliases: [],
    footId: 204800,
    servantClass: "archer",
    inNa: false,
  },
  {
    name: "Cu Chulainn",
    aliases: [],
    footId: 300100,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Diarmuid Ua Duibhne",
    aliases: [],
    footId: 300200,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Vlad III (EXTRA)",
    aliases: [],
    footId: 300300,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Karna",
    aliases: [],
    footId: 300400,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Elisabeth Bathory",
    aliases: [],
    footId: 300500,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Musashibou Benkei",
    aliases: [],
    footId: 300600,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Cu Chulainn (Prototype)",
    aliases: [],
    footId: 300700,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Enkidu",
    aliases: [],
    footId: 300800,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Leonidas I",
    aliases: [],
    footId: 300900,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Romulus",
    aliases: [],
    footId: 301000,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Fionn mac Cumhaill",
    aliases: [],
    footId: 301100,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Brynhild",
    aliases: [],
    footId: 301200,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Scathach",
    aliases: [],
    footId: 301300,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Houzouin Inshun",
    aliases: [],
    footId: 301400,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Hektor",
    aliases: [],
    footId: 301600,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Li Shuwen",
    aliases: [],
    footId: 301700,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Artoria Pendragon (Lancer Alter)",
    aliases: ["Altria Pendragon (Lancer Alter)", "Lalter"],
    footId: 301900,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Artoria Pendragon (Lancer)",
    aliases: ["Altria Pendragon (Lancer)", "Lartoria"],
    footId: 302000,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Tamamo-no-Mae (Lancer)",
    aliases: ["Summer Tamamo"],
    footId: 302400,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Kiyohime (Lancer)",
    aliases: ["Summer Kiyohime"],
    footId: 302500,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Jeanne d'Arc Alter Santa Lily",
    aliases: [],
    footId: 302600,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Medusa (Lancer)",
    aliases: ["Ana", "Medusa Lily"],
    footId: 302700,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Jaguar Warrior",
    aliases: [],
    footId: 302800,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Minamoto-no-Raikou (Lancer)",
    aliases: ["Summer Raikou"],
    footId: 302900,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Parvati",
    aliases: [],
    footId: 303000,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Nezha",
    aliases: [],
    footId: 303100,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Ereshkigal",
    aliases: [],
    footId: 303200,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Valkyrie",
    aliases: ["Ortlinde", "Hildr", "Thrud"],
    footId: 303300,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Ibaraki-Douji (Lancer)",
    aliases: ["Summer Ibaraki", "Summer Banana"],
    footId: 303400,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Qin Liangyu",
    aliases: [],
    footId: 303500,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Bradamante",
    aliases: [],
    footId: 303600,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Nagao Kagetora",
    aliases: [],
    footId: 303800,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Gareth",
    aliases: [],
    footId: 303900,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Mysterious Alter Ego Λ",
    aliases: ["Summer Melt", "Mysterious Alter Ego Lambda"],
    footId: 304000,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Caenis",
    aliases: [],
    footId: 304100,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Romulus=Quirinus",
    aliases: [],
    footId: 304200,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Utsumi Erice",
    aliases: [],
    footId: 304300,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Yu Mei-ren (Lancer)",
    aliases: ["Summer Gucchan", "Summer Yu"],
    footId: 304400,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Vritra",
    aliases: [],
    footId: 304600,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Percival",
    aliases: [],
    footId: 304700,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Melusine",
    aliases: ["Fairy Knight Lancelot", "Tam Lin Lancelot"],
    footId: 304800,
    servantClass: "lancer",
    inNa: true,
  },
  {
    name: "Mary Anning",
    aliases: [],
    footId: 304900,
    servantClass: "lancer",
    inNa: false,
  },
  {
    name: "Sakamoto Ryouma (Lancer)",
    aliases: [],
    footId: 305000,
    servantClass: "lancer",
    inNa: false,
  },
  {
    name: "Don Quixote",
    aliases: [],
    footId: 305100,
    servantClass: "lancer",
    inNa: false,
  },
  {
    name: "Britomart",
    aliases: [],
    footId: 305300,
    servantClass: "lancer",
    inNa: false,
  },
  {
    name: "Bhima",
    aliases: [],
    footId: 305400,
    servantClass: "lancer",
    inNa: false,
  },
  {
    name: "Medusa",
    aliases: [],
    footId: 400100,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Iskandar",
    aliases: [],
    footId: 400200,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Francis Drake",
    aliases: [],
    footId: 400300,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Astolfo",
    aliases: [],
    footId: 400400,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Georgios",
    aliases: [],
    footId: 400600,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Edward Teach",
    aliases: ["Blackbeard"],
    footId: 400800,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Anne Bonny & Mary Read",
    aliases: [],
    footId: 400900,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Boudica",
    aliases: [],
    footId: 401100,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Ozymandias",
    aliases: [],
    footId: 401200,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Queen Medb",
    aliases: [],
    footId: 401300,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Ushiwakamaru",
    aliases: [],
    footId: 401400,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Alexander",
    aliases: [],
    footId: 401500,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Marie Antoinette",
    aliases: [],
    footId: 401700,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Quetzalcoatl",
    aliases: [],
    footId: 401800,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Martha",
    aliases: [],
    footId: 401900,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Artoria Pendragon (Santa Alter)",
    aliases: ["Altria Pendragon (Santa Alter)"],
    footId: 402200,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Sakata Kintoki (Rider)",
    aliases: [],
    footId: 402300,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Mordred (Rider)",
    aliases: ["Summer Mordred"],
    footId: 402400,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Christopher Columbus",
    aliases: ["Rider of Resistance"],
    footId: 402500,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Ishtar (Rider)",
    aliases: ["Summer Ishtar"],
    footId: 402600,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Artoria Pendragon (Rider Alter)",
    aliases: ["Altria Pendragon (Rider Alter)", "Summer Salter", "Maid Alter"],
    footId: 402700,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Ivan the Terrible",
    aliases: [],
    footId: 402800,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Achilles",
    aliases: [],
    footId: 402900,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Sakamoto Ryouma",
    aliases: [],
    footId: 403000,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Red Hare",
    aliases: [],
    footId: 403100,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Sima Yi (Reines)",
    aliases: [],
    footId: 403200,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Bartholomew Roberts",
    aliases: [],
    footId: 403400,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Leonardo da Vinci (Rider)",
    aliases: [],
    footId: 403500,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Carmilla (Rider)",
    aliases: ["Summer Carmilla"],
    footId: 403600,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Nemo",
    aliases: [],
    footId: 403700,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Odysseus",
    aliases: [],
    footId: 403800,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Mandricardo",
    aliases: [],
    footId: 403900,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Europa",
    aliases: [],
    footId: 404000,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Murasaki Shikibu (Rider)",
    aliases: ["Summer Murasaki", "Summer Kaoruko"],
    footId: 404100,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Habetrot",
    aliases: ["Habbycat", "Habenyan"],
    footId: 404200,
    servantClass: "rider",
    inNa: true,
  },
  {
    name: "Taigong Wang",
    aliases: [],
    footId: 404300,
    servantClass: "rider",
    inNa: false,
  },
  {
    name: "Dobrynya Nikitich",
    aliases: [],
    footId: 404400,
    servantClass: "rider",
    inNa: false,
  },
  {
    name: "Caenis (Rider)",
    aliases: ["Summer Caenis"],
    footId: 404500,
    servantClass: "rider",
    inNa: false,
  },
  {
    name: "Elisabeth Bathory (Cinderella)",
    aliases: [],
    footId: 404600,
    servantClass: "rider",
    inNa: false,
  },
  {
    name: "Constantine XI",
    aliases: [],
    footId: 404700,
    servantClass: "rider",
    inNa: false,
  },
  {
    name: "Kyokutei Bakin",
    aliases: [],
    footId: 404800,
    servantClass: "rider",
    inNa: false,
  },
  {
    name: "Huang Feihu",
    aliases: [],
    footId: 404900,
    servantClass: "rider",
    inNa: false,
  },
  {
    name: "Medea",
    aliases: [],
    footId: 500100,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Gilles de Rais",
    aliases: [],
    footId: 500200,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Tamamo-no-Mae",
    aliases: [],
    footId: 500300,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Nursery Rhyme",
    aliases: [],
    footId: 500400,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Hans Christian Andersen",
    aliases: [],
    footId: 500500,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "William Shakespeare",
    aliases: [],
    footId: 500700,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Merlin",
    aliases: [],
    footId: 500800,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Paracelsus von Hohenheim",
    aliases: [],
    footId: 501000,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Charles Babbage",
    aliases: [],
    footId: 501100,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Nitocris",
    aliases: ["Best Girl Don't @ Me"],
    footId: 501200,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Mephistopheles",
    aliases: [],
    footId: 501400,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Wolfgang Amadeus Mozart",
    aliases: [],
    footId: 501500,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Geronimo",
    aliases: [],
    footId: 501600,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Medea (Lily)",
    aliases: [],
    footId: 501700,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Gilgamesh (Caster)",
    aliases: [],
    footId: 501800,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Zhuge Liang (Lord El-Melloi II)",
    aliases: ["Waver Velvet"],
    footId: 501900,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Irisviel (Holy Grail)",
    aliases: [],
    footId: 502000,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Cu Chulainn (Caster)",
    aliases: [],
    footId: 502100,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Xuanzang Sanzang",
    aliases: [],
    footId: 502200,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Helena Blavatsky",
    aliases: [],
    footId: 502300,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Thomas Edison",
    aliases: [],
    footId: 502500,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Elisabeth Bathory (Halloween)",
    aliases: [],
    footId: 502600,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Marie Antoinette (Caster)",
    aliases: ["Summer Marie"],
    footId: 502700,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Illyasviel von Einzbern",
    aliases: [],
    footId: 502800,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Scheherazade",
    aliases: ["Caster of the Nightless City"],
    footId: 503000,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Nero Claudius (Caster)",
    aliases: ["Summer Nero"],
    footId: 503200,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Circe",
    aliases: ["Caster of Okeanos"],
    footId: 503300,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Queen of Sheba",
    aliases: ["Caster of Midrash"],
    footId: 503400,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Anastasia",
    aliases: [],
    footId: 503500,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Avicebron",
    aliases: [],
    footId: 503600,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Sieg",
    aliases: [],
    footId: 503800,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Scathach-Skadi",
    aliases: [],
    footId: 503900,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Shuten-Douji (Caster)",
    aliases: [],
    footId: 504000,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Miyu Edelfelt",
    aliases: [],
    footId: 504100,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Murasaki Shikibu",
    aliases: ["Kaoruko"],
    footId: 504200,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Asclepius",
    aliases: [],
    footId: 504300,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Chen Gong",
    aliases: [],
    footId: 504400,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Artoria Caster",
    aliases: ["Altria Caster", "Castoria"],
    footId: 504500,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Miss Crane",
    aliases: [],
    footId: 504600,
    servantClass: "caster",
    inNa: true,
  },
  {
    name: "Daikokuten",
    aliases: [],
    footId: 504700,
    servantClass: "caster",
    inNa: false,
  },
  {
    name: "Charlotte Corday (Caster)",
    aliases: ["Summer Charlotte"],
    footId: 504800,
    servantClass: "caster",
    inNa: false,
  },
  {
    name: "Izumo no Okuni",
    aliases: [],
    footId: 504900,
    servantClass: "caster",
    inNa: false,
  },
  {
    name: "Martha (Santa)",
    aliases: [],
    footId: 505000,
    servantClass: "caster",
    inNa: false,
  },
  {
    name: "Zhang Jiao",
    aliases: [],
    footId: 505100,
    servantClass: "caster",
    inNa: false,
  },
  {
    name: "Wu Zetian (Caster)",
    aliases: ["Summer Wu"],
    footId: 505200,
    servantClass: "caster",
    inNa: false,
  },
  {
    name: "Sasaki Kojirou",
    aliases: [],
    footId: 600100,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Hassan of the Cursed Arm",
    aliases: [],
    footId: 600200,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Hassan of the Hundred Personas",
    aliases: ["Hassan of the Hundred Faces"],
    footId: 600300,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Jack the Ripper",
    aliases: [],
    footId: 600500,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Henry Jekyll & Hyde",
    aliases: [],
    footId: 600700,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Cleopatra",
    aliases: [],
    footId: 600800,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Hassan of the Serenity",
    aliases: [],
    footId: 600900,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Stheno",
    aliases: [],
    footId: 601000,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Jing Ke",
    aliases: [],
    footId: 601100,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Charles-Henri Sanson",
    aliases: [],
    footId: 601200,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Phantom of the Opera",
    aliases: [],
    footId: 601300,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Mata Hari",
    aliases: [],
    footId: 601400,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Emiya (Assassin)",
    aliases: [],
    footId: 601500,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Carmilla",
    aliases: [],
    footId: 601700,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Mysterious Heroine X",
    aliases: ["MHX"],
    footId: 601800,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: 'Fuuma "Evil-wind" Kotarou',
    aliases: [],
    footId: 601900,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Shuten-Douji",
    aliases: [],
    footId: 602100,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Ryougi Shiki (Assassin)",
    aliases: [],
    footId: 602300,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Scathach (Assassin)",
    aliases: ["Summer Scathach"],
    footId: 602400,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: '"First Hassan"',
    aliases: ["King Hassan", '"The Old Man of the Mountain"'],
    footId: 602500,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Yan Qing",
    aliases: ["Assassin of Shinjuku"],
    footId: 602600,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Wu Zetian",
    aliases: ["Nite Brite", "Fuya-chan", "Assassin of the Nightless City"],
    footId: 602700,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Nitocris (Assassin)",
    aliases: ["Summer Nitocris", "Medjed", "Best Girl Again Don't @ Me"],
    footId: 602800,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Mochizuki Chiyome",
    aliases: ["Assassin of Paraiso"],
    footId: 602900,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: 'Katou "Black Kite" Danzo',
    aliases: [],
    footId: 603000,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Osakabehime",
    aliases: ["Okki", "Batty"],
    footId: 603100,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Semiramis",
    aliases: [],
    footId: 603200,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Okada Izo",
    aliases: [],
    footId: 603300,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Ushiwakamaru (Assassin)",
    aliases: ["Summer Ushiwakamaru"],
    footId: 603400,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Yu Mei-ren",
    aliases: ["Gucchan", "Consort Yu"],
    footId: 603500,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Li Shuwen (Assassin)",
    aliases: ["Old Li"],
    footId: 603600,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Kama",
    aliases: [],
    footId: 603700,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Charlotte Corday",
    aliases: [],
    footId: 603800,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Gray",
    aliases: [],
    footId: 603900,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Okita J. Souji",
    aliases: ["Summer Okita"],
    footId: 604000,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Kiichi Hogen",
    aliases: [],
    footId: 604100,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Koyanskaya of Light",
    aliases: ["Vitch Light"],
    footId: 604200,
    servantClass: "assassin",
    inNa: true,
  },
  {
    name: "Valkyrie (Assassin)",
    aliases: ["Ortlinde (Assassin)", "Hildr (Assassin)", "Thrud (Assassin)"],
    footId: 604300,
    servantClass: "assassin",
    inNa: false,
  },
  {
    name: "Huyan Zhuo",
    aliases: [],
    footId: 604600,
    servantClass: "assassin",
    inNa: false,
  },
  {
    name: "Tezcatlipoca",
    aliases: [],
    footId: 604700,
    servantClass: "assassin",
    inNa: false,
  },
  {
    name: "Locusta",
    aliases: [],
    footId: 604800,
    servantClass: "assassin",
    inNa: false,
  },
  {
    name: "Kashin Koji",
    aliases: [],
    footId: 604900,
    servantClass: "assassin",
    inNa: false,
  },
  {
    name: "Heracles",
    aliases: ["Hercules"],
    footId: 700100,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Lancelot",
    aliases: [],
    footId: 700200,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Lu Bu Fengxian",
    aliases: [],
    footId: 700300,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Frankenstein",
    aliases: [],
    footId: 700400,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Spartacus",
    aliases: [],
    footId: 700500,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Sakata Kintoki",
    aliases: [],
    footId: 700600,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Vlad III",
    aliases: [],
    footId: 700700,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Beowulf",
    aliases: [],
    footId: 700800,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Asterios",
    aliases: [],
    footId: 700900,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Caligula",
    aliases: [],
    footId: 701000,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Darius III",
    aliases: [],
    footId: 701100,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Kiyohime",
    aliases: [],
    footId: 701300,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Florence Nightingale",
    aliases: [],
    footId: 701400,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Eric Bloodaxe",
    aliases: [],
    footId: 701500,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Tamamo Cat",
    aliases: [],
    footId: 701600,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Cu Chulainn (Alter)",
    aliases: [],
    footId: 702000,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Ibaraki-Douji",
    aliases: [],
    footId: 702200,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Minamoto-no-Raikou",
    aliases: [],
    footId: 702300,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Mysterious Heroine X (Alter)",
    aliases: ["MHXA"],
    footId: 702400,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Hijikata Toshizo",
    aliases: [],
    footId: 702500,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Chacha",
    aliases: [],
    footId: 702600,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Penthesilea",
    aliases: ["Berserker of El Dorado"],
    footId: 702700,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Paul Bunyan",
    aliases: [],
    footId: 702800,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Oda Nobunaga (Berserker)",
    aliases: ["Summer Nobunaga"],
    footId: 702900,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Atalante (Alter)",
    aliases: ["Nyalter"],
    footId: 703000,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Jeanne d'Arc (Berserker Alter)",
    aliases: ["Summer Jalter"],
    footId: 703100,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Xiang Yu",
    aliases: [],
    footId: 703200,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Arjuna (Alter)",
    aliases: ["Junao"],
    footId: 703300,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Salome",
    aliases: [],
    footId: 703400,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Mori Nagayoshi",
    aliases: [],
    footId: 703500,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Kijyo Koyo",
    aliases: [],
    footId: 703700,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Brynhild (Berserker)",
    aliases: ["Summer Brynhild"],
    footId: 703800,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Galatea",
    aliases: [],
    footId: 703900,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Morgan",
    aliases: [],
    footId: 704000,
    servantClass: "berserker",
    inNa: true,
  },
  {
    name: "Sei Shounagon (Berserker)",
    aliases: ["Summer Nagiko", "Summer Sei"],
    footId: 704100,
    servantClass: "berserker",
    inNa: false,
  },
  {
    name: "Kriemhild",
    aliases: [],
    footId: 704200,
    servantClass: "berserker",
    inNa: false,
  },
  {
    name: "Ibuki-Douji (Berserker)",
    aliases: ["Summer Ibuki"],
    footId: 704300,
    servantClass: "berserker",
    inNa: false,
  },
  {
    name: "Sen no Rikyu",
    aliases: [],
    footId: 704400,
    servantClass: "berserker",
    inNa: false,
  },
  {
    name: "Duryodhana",
    aliases: [],
    footId: 704600,
    servantClass: "berserker",
    inNa: false,
  },
  {
    name: "Mash Kyrielight",
    aliases: ["Mashu", "Shielder"],
    footId: 800100,
    servantClass: "shielder",
    inNa: true,
  },
  {
    name: "Jeanne d'Arc",
    aliases: [],
    footId: 900100,
    servantClass: "ruler",
    inNa: true,
  },
  {
    name: "Amakusa Shirou",
    aliases: [],
    footId: 900200,
    servantClass: "ruler",
    inNa: true,
  },
  {
    name: "Martha (Ruler)",
    aliases: ["Summer Martha"],
    footId: 900400,
    servantClass: "ruler",
    inNa: true,
  },
  {
    name: "Qin Shi Huang",
    aliases: ["QSH"],
    footId: 900600,
    servantClass: "ruler",
    inNa: true,
  },
  {
    name: "Quetzalcoatl (Samba/Santa)",
    aliases: [],
    footId: 900700,
    servantClass: "ruler",
    inNa: true,
  },
  {
    name: "Astraea",
    aliases: ["Luvia Edelfelt"],
    footId: 900800,
    servantClass: "ruler",
    inNa: true,
  },
  {
    name: "Artoria Pendragon (Ruler)",
    aliases: ["Altria Pendragon (Ruler)", "Summer Lartoria", "Bunnytoria"],
    footId: 900900,
    servantClass: "ruler",
    inNa: true,
  },
  {
    name: "Himiko",
    aliases: [],
    footId: 901000,
    servantClass: "ruler",
    inNa: true,
  },
  {
    name: "Amor (Caren)",
    aliases: ["God Caren", "Caren C. Hortensia"],
    footId: 901100,
    servantClass: "ruler",
    inNa: true,
  },
  {
    name: "Leonardo da Vinci (Ruler)",
    aliases: ["Summer da Vinci"],
    footId: 901200,
    servantClass: "ruler",
    inNa: false,
  },
  {
    name: "James Moriarty (Ruler)",
    aliases: [],
    footId: 901300,
    servantClass: "ruler",
    inNa: false,
  },
  {
    name: "Scathach-Skadi (Ruler)",
    aliases: ["Summer Skadi"],
    footId: 901400,
    servantClass: "ruler",
    inNa: false,
  },
  {
    name: "Iyo",
    aliases: [],
    footId: 901500,
    servantClass: "ruler",
    inNa: false,
  },
  {
    name: "Pope Johanna",
    aliases: ["High Priestess Johanna", "Popess Johanna"],
    footId: 901600,
    servantClass: "ruler",
    inNa: false,
  },
  {
    name: "Passionlip",
    aliases: [],
    footId: 1000100,
    servantClass: "alter-ego",
    inNa: true,
  },
  {
    name: "Meltryllis",
    aliases: ["Meltlillith"],
    footId: 1000200,
    servantClass: "alter-ego",
    inNa: true,
  },
  {
    name: "Sessyoin Kiara",
    aliases: [],
    footId: 1000300,
    servantClass: "alter-ego",
    inNa: true,
  },
  {
    name: "Mecha Eli-chan",
    aliases: [],
    footId: 1000400,
    servantClass: "alter-ego",
    inNa: true,
  },
  {
    name: "Mecha Eli-chan Mk.II",
    aliases: [],
    footId: 1000500,
    servantClass: "alter-ego",
    inNa: true,
  },
  {
    name: "Okita Souji (Alter)",
    aliases: ["Okitan"],
    footId: 1000700,
    servantClass: "alter-ego",
    inNa: true,
  },
  {
    name: "Sitonai",
    aliases: [],
    footId: 1000800,
    servantClass: "alter-ego",
    inNa: true,
  },
  {
    name: "Kingprotea",
    aliases: [],
    footId: 1000900,
    servantClass: "alter-ego",
    inNa: true,
  },
  {
    name: "Ashiya Douman",
    aliases: ["Caster of Limbo"],
    footId: 1001000,
    servantClass: "alter-ego",
    inNa: true,
  },
  {
    name: "Manannan mac Lir (Bazett)",
    aliases: [],
    footId: 1001100,
    servantClass: "alter-ego",
    inNa: false,
  },
  {
    name: "Taisui Xingjun",
    aliases: [],
    footId: 1001200,
    servantClass: "alter-ego",
    inNa: false,
  },
  {
    name: "Super Bunyan",
    aliases: [],
    footId: 1001300,
    servantClass: "alter-ego",
    inNa: false,
  },
  {
    name: "Xu Fu",
    aliases: [],
    footId: 1001400,
    servantClass: "alter-ego",
    inNa: false,
  },
  {
    name: "Grigori Rasputin",
    aliases: ["Kirei Kotomine"],
    footId: 1001500,
    servantClass: "alter-ego",
    inNa: false,
  },
  {
    name: "Larva/Tiamat",
    aliases: [],
    footId: 1001600,
    servantClass: "alter-ego",
    inNa: false,
  },
  {
    name: "Aŋra Mainiiu",
    aliases: ["Angra Mainyu"],
    footId: 1100100,
    servantClass: "avenger",
    inNa: true,
  },
  {
    name: "Edmond Dantes",
    aliases: ["The Count of Monte Cristo"],
    footId: 1100200,
    servantClass: "avenger",
    inNa: true,
  },
  {
    name: "Jeanne d'Arc (Alter)",
    aliases: ["Jalter"],
    footId: 1100300,
    servantClass: "avenger",
    inNa: true,
  },
  {
    name: "Gorgon",
    aliases: [],
    footId: 1100400,
    servantClass: "avenger",
    inNa: true,
  },
  {
    name: "Hessian Lobo",
    aliases: ["Avenger of Shinjuku", "Rider of Shinjuku"],
    footId: 1100500,
    servantClass: "avenger",
    inNa: true,
  },
  {
    name: "Antonio Salieri",
    aliases: [],
    footId: 1100600,
    servantClass: "avenger",
    inNa: true,
  },
  {
    name: "Demon King Nobunaga",
    aliases: ["Maou Nobunaga"],
    footId: 1100700,
    servantClass: "avenger",
    inNa: true,
  },
  {
    name: "Space Ishtar",
    aliases: ["Spishtar"],
    footId: 1100900,
    servantClass: "avenger",
    inNa: true,
  },
  {
    name: "Taira-no-Kagekiyo",
    aliases: [],
    footId: 1101000,
    servantClass: "avenger",
    inNa: true,
  },
  {
    name: "Kama (Avenger)",
    aliases: ["Summer Kama"],
    footId: 1101100,
    servantClass: "avenger",
    inNa: false,
  },
  {
    name: "Mysterious Ranmaru X",
    aliases: [],
    footId: 1101200,
    servantClass: "avenger",
    inNa: false,
  },
  {
    name: "Utsumi Erice (Avenger)",
    aliases: ["Summer Erice"],
    footId: 1101400,
    servantClass: "avenger",
    inNa: false,
  },
  {
    name: "Nitocris (Alter)",
    aliases: ["Also Best Girl Don't @ Me"],
    footId: 1101500,
    servantClass: "avenger",
    inNa: false,
  },
  {
    name: "BB",
    aliases: [],
    footId: 2300100,
    servantClass: "moon-cancer",
    inNa: true,
  },
  {
    name: "BB (Summer)",
    aliases: ["Summer BB"],
    footId: 2300200,
    servantClass: "moon-cancer",
    inNa: true,
  },
  {
    name: "Jinako Carigiri",
    aliases: ["Great Stone Statue God", "Ganesha"],
    footId: 2300300,
    servantClass: "moon-cancer",
    inNa: true,
  },
  {
    name: "Sessyoin Kiara (Moon Cancer)",
    aliases: ["Summer Kiara"],
    footId: 2300400,
    servantClass: "moon-cancer",
    inNa: true,
  },
  {
    name: "Archetype: Earth",
    aliases: ["Arcueid Brunestud"],
    footId: 2300500,
    servantClass: "moon-cancer",
    inNa: false,
  },
  {
    name: "Abigail Williams",
    aliases: ["Abby"],
    footId: 2500100,
    servantClass: "foreigner",
    inNa: true,
  },
  {
    name: "Katsushika Hokusai",
    aliases: ["Oei"],
    footId: 2500200,
    servantClass: "foreigner",
    inNa: true,
  },
  {
    name: "Mysterious Heroine XX",
    aliases: ["MHXX"],
    footId: 2500300,
    servantClass: "foreigner",
    inNa: true,
  },
  {
    name: "Yang Guifei",
    aliases: ["Yuyu"],
    footId: 2500400,
    servantClass: "foreigner",
    inNa: true,
  },
  {
    name: "Voyager",
    aliases: [],
    footId: 2500500,
    servantClass: "foreigner",
    inNa: true,
  },
  {
    name: "Van Gogh",
    aliases: [],
    footId: 2500600,
    servantClass: "foreigner",
    inNa: true,
  },
  {
    name: "Abigail Williams (Summer)",
    aliases: ["Summer Abby"],
    footId: 2500700,
    servantClass: "foreigner",
    inNa: true,
  },
  {
    name: "Mysterious Idol X (Alter)",
    aliases: ["MIXA"],
    footId: 2500800,
    servantClass: "foreigner",
    inNa: true,
  },
  {
    name: "Koyanskaya of Darkness",
    aliases: ["Vitch Dark"],
    footId: 2500900,
    servantClass: "foreigner",
    inNa: false,
  },
  {
    name: "Jacques de Molay",
    aliases: [],
    footId: 2501000,
    servantClass: "foreigner",
    inNa: false,
  },
  {
    name: "Kukulkan",
    aliases: [],
    footId: 2501100,
    servantClass: "foreigner",
    inNa: false,
  },
  {
    name: "Oberon",
    aliases: [],
    footId: 2800100,
    servantClass: "pretender",
    inNa: true,
  },
  {
    name: "Hephaestion",
    aliases: [],
    footId: 2800200,
    servantClass: "pretender",
    inNa: false,
  },
  {
    name: "Lady Avalon",
    aliases: ["Merlin (Prototype)"],
    footId: 2800300,
    servantClass: "pretender",
    inNa: false,
  },
  {
    name: "Nine-Tattoo Dragon Elisa",
    aliases: [],
    footId: 2800400,
    servantClass: "pretender",
    inNa: false,
  },
  {
    name: "Tlaloc",
    aliases: [],
    footId: 2800500,
    servantClass: "pretender",
    inNa: false,
  },
  {
    name: "Sodom's Beast/Draco",
    aliases: [],
    footId: 3300100,
    servantClass: "beast",
    inNa: false,
  },
];
